// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using RegistrationPortal.Server.Data;

#nullable disable

namespace RegistrationPortal.Server.Migrations
{
    [DbContext(typeof(RegistrationPortalDbContext))]
    partial class RegistrationPortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("BINARY_CI")
                .HasAnnotation("ProductVersion", "11.2.0.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistrationPortal.Server.Entities.AccountMast", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("id");

                    b.Property<string>("ActCAbbsts")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("act_c_abbsts");

                    b.Property<string>("ActCActsts")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("act_c_actsts");

                    b.Property<string>("ActCAtm")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("act_c_atm");

                    b.Property<string>("ActCChqfac")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("act_c_chqfac");

                    b.Property<string>("ActCInternet")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("act_c_internet");

                    b.Property<string>("ActCIntrotype")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("act_c_introtype");

                    b.Property<string>("ActCName")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)")
                        .HasColumnName("act_c_name");

                    b.Property<string>("ActCOcccode")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("act_c_occcode");

                    b.Property<string>("ActCOdsts")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("act_c_odsts");

                    b.Property<string>("ActCOpmode")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("act_c_opmode");

                    b.Property<string>("ActCOrgn")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("act_c_orgn");

                    b.Property<string>("ActCTelebnk")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("act_c_telebnk");

                    b.Property<string>("ActCType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("act_c_type");

                    b.Property<DateTime?>("ActDClosdt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("act_d_closdt");

                    b.Property<DateTime?>("ActDOpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("act_d_opdate");

                    b.Property<decimal?>("ActIIntroid")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("act_i_introid");

                    b.Property<decimal?>("ActITrbrcode")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("act_i_trbrcode");

                    b.Property<string>("AuthCBy")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("auth_c_by");

                    b.Property<string>("BranchCCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("branch_c_code");

                    b.Property<string>("CloseCReason")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("close_c_reason");

                    b.Property<string>("CurrencyCCode")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("currency_c_code");

                    b.Property<decimal>("CustINo")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("cust_i_no");

                    b.Property<string>("CustId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("cust_id");

                    b.Property<string>("EnteredCBy")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("entered_c_by");

                    b.Property<string>("GroupCCode")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("group_c_code");

                    b.Property<string>("IntroCRem")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("intro_c_rem");

                    b.Property<string>("WithdrawCFlag")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("withdraw_c_flag");

                    b.HasKey("Id")
                        .HasName("pk_account_mast");

                    b.HasIndex("CustId");

                    b.ToTable("account_mast", "SSDBONLINE");
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.CustMast", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("id");

                    b.Property<string>("BranchCCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR2(10 BYTE)")
                        .HasColumnName("branch_c_code");

                    b.Property<string>("CountryCCode")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("country_c_code");

                    b.Property<string>("CustCAuthority")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("cust_c_authority");

                    b.Property<string>("CustCCaste")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("cust_c_caste");

                    b.Property<string>("CustCCitizenship")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("cust_c_citizenship");

                    b.Property<string>("CustCCountrybrith")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("cust_c_countrybrith");

                    b.Property<string>("CustCEmployer")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("cust_c_employer");

                    b.Property<string>("CustCEngfname")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2(250 BYTE)")
                        .HasColumnName("cust_c_engfname");

                    b.Property<string>("CustCEngfoname")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2(250 BYTE)")
                        .HasColumnName("cust_c_engfoname");

                    b.Property<string>("CustCEngsname")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2(250 BYTE)")
                        .HasColumnName("cust_c_engsname");

                    b.Property<string>("CustCEngtname")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2(250 BYTE)")
                        .HasColumnName("cust_c_engtname");

                    b.Property<string>("CustCFname")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2(250 BYTE)")
                        .HasColumnName("cust_c_fname");

                    b.Property<string>("CustCFoname")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2(250 BYTE)")
                        .HasColumnName("cust_c_foname");

                    b.Property<string>("CustCHigheducation")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("cust_c_higheducation");

                    b.Property<string>("CustCMaritalsts")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 BYTE)")
                        .HasColumnName("cust_c_maritalsts");

                    b.Property<string>("CustCMname")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2(250 BYTE)")
                        .HasColumnName("cust_c_mname");

                    b.Property<string>("CustCName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2(250 BYTE)")
                        .HasColumnName("cust_c_name");

                    b.Property<string>("CustCNationality")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100 BYTE)")
                        .HasColumnName("cust_c_nationality");

                    b.Property<string>("CustCOccupation")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100 BYTE)")
                        .HasColumnName("cust_c_occupation");

                    b.Property<string>("CustCPCity")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("cust_c_pcity");

                    b.Property<string>("CustCPadd1")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100 BYTE)")
                        .HasColumnName("cust_c_padd1");

                    b.Property<string>("CustCReligion")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 BYTE)")
                        .HasColumnName("cust_c_religion");

                    b.Property<string>("CustCSex")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR2(10 BYTE)")
                        .HasColumnName("cust_c_sex");

                    b.Property<string>("CustCSname")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2(250 BYTE)")
                        .HasColumnName("cust_c_sname");

                    b.Property<string>("CustCStatebrith")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR2(10 BYTE)")
                        .HasColumnName("cust_c_statebrith");

                    b.Property<string>("CustCTname")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2(250 BYTE)")
                        .HasColumnName("cust_c_tname");

                    b.Property<string>("CustCWife1")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2(250 BYTE)")
                        .HasColumnName("cust_c_wife1");

                    b.Property<DateTime?>("CustDBdate")
                        .HasColumnType("DATE")
                        .HasColumnName("cust_d_bdate");

                    b.Property<DateTime>("CustDEntrydt")
                        .HasColumnType("DATE")
                        .HasColumnName("cust_d_entrydt");

                    b.Property<decimal?>("CustFAvgmonth")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("cust_f_avgmonth");

                    b.Property<decimal?>("CustFIncome")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("cust_f_income");

                    b.Property<long>("CustIId")
                        .HasColumnType("NUMBER(18,0)")
                        .HasColumnName("cust_i_id");

                    b.Property<string>("CustIIdentify")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 BYTE)")
                        .HasColumnName("cust_i_identify");

                    b.Property<string>("EmailCAdd")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("email_c_add");

                    b.Property<long?>("HomeINumber")
                        .HasColumnType("NUMBER(18,0)")
                        .HasColumnName("home_i_number");

                    b.Property<string>("HusbCName")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100 BYTE)")
                        .HasColumnName("husb_c_name");

                    b.Property<string>("IdCIssplace")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("id_c_issplace");

                    b.Property<string>("IdCNo")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("id_c_no");

                    b.Property<string>("IdCNo2")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("id_c_no2");

                    b.Property<string>("IdCType")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("id_c_type");

                    b.Property<string>("IdCType2")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("id_c_type2");

                    b.Property<DateTime?>("IdDExpdate")
                        .HasColumnType("DATE")
                        .HasColumnName("id_d_expdate");

                    b.Property<DateTime?>("IdDIssdate")
                        .HasColumnType("DATE")
                        .HasColumnName("id_d_issdate");

                    b.Property<string>("MobileCNo")
                        .HasMaxLength(18)
                        .HasColumnType("VARCHAR2(18 BYTE)")
                        .HasColumnName("mobile_c_no");

                    b.Property<string>("PlaceCBirth")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100 BYTE)")
                        .HasColumnName("place_c_birth");

                    b.Property<string>("ReviewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("review_status");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("status");

                    b.Property<string>("TradeCNameenglish")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR2(250 BYTE)")
                        .HasColumnName("trade_c_nameenglish");

                    b.HasKey("Id")
                        .HasName("pk_cust_mast");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_cust_mast_status");

                    b.ToTable("cust_mast", "SSDBONLINE");
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.CustomerDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("customer_id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("document_type");

                    b.Property<decimal>("FileSize")
                        .HasColumnType("NUMBER")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500 BYTE)")
                        .HasColumnName("file_url");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100 BYTE)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255 BYTE)")
                        .HasColumnName("original_file_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer_documents");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_document_customer_id");

                    b.HasIndex("CustomerId", "DocumentType")
                        .HasDatabaseName("ix_document_customer_type");

                    b.ToTable("customer_documents", "SSDBONLINE");
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.CustomerFatca", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("id");

                    b.Property<string>("ATIN")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 BYTE)")
                        .HasColumnName("atin");

                    b.Property<string>("CitizenshipCountries")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500 BYTE)")
                        .HasColumnName("citizenship_countries");

                    b.Property<string>("Country1NoTinExplanation")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500 BYTE)")
                        .HasColumnName("country1_no_tin_explanation");

                    b.Property<string>("Country1NoTinReason")
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2(1 BYTE)")
                        .HasColumnName("country1_no_tin_reason");

                    b.Property<string>("Country1TIN")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("country1_tin");

                    b.Property<string>("Country1TaxJurisdiction")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100 BYTE)")
                        .HasColumnName("country1_tax_jurisdiction");

                    b.Property<string>("Country2NoTinExplanation")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500 BYTE)")
                        .HasColumnName("country2_no_tin_explanation");

                    b.Property<string>("Country2NoTinReason")
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2(1 BYTE)")
                        .HasColumnName("country2_no_tin_reason");

                    b.Property<string>("Country2TIN")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("country2_tin");

                    b.Property<string>("Country2TaxJurisdiction")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100 BYTE)")
                        .HasColumnName("country2_tax_jurisdiction");

                    b.Property<string>("Country3NoTinExplanation")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500 BYTE)")
                        .HasColumnName("country3_no_tin_explanation");

                    b.Property<string>("Country3NoTinReason")
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2(1 BYTE)")
                        .HasColumnName("country3_no_tin_reason");

                    b.Property<string>("Country3TIN")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("country3_tin");

                    b.Property<string>("Country3TaxJurisdiction")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100 BYTE)")
                        .HasColumnName("country3_tax_jurisdiction");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 BYTE)")
                        .HasColumnName("customer_id");

                    b.Property<string>("HasImmigrantVisa")
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1 BYTE)")
                        .HasColumnName("has_immigrant_visa");

                    b.Property<string>("HasOtherCountriesResidency")
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1 BYTE)")
                        .HasColumnName("has_other_countries_residency");

                    b.Property<string>("ITIN")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 BYTE)")
                        .HasColumnName("itin");

                    b.Property<string>("IsUsPerson")
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1 BYTE)")
                        .HasColumnName("is_us_person");

                    b.Property<string>("PermanentResidencyStates")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500 BYTE)")
                        .HasColumnName("permanent_residency_states");

                    b.Property<string>("SSN")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 BYTE)")
                        .HasColumnName("ssn");

                    b.Property<string>("SoleSudanResidencyConfirmed")
                        .HasMaxLength(10)
                        .HasColumnType("CHAR(10 BYTE)")
                        .HasColumnName("sole_sudan_residency_confirmed");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer_fatca");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_fatca_customer_id");

                    b.ToTable("customer_fatca", "SSDBONLINE");
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.Identity.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERMISSION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ACTION");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MODULE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Id")
                        .HasName("PK_PERMISSIONS");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_PERMISSIONS_NAME");

                    b.HasIndex("Module", "Action")
                        .IsUnique()
                        .HasDatabaseName("IX_PERMISSIONS_MODULE_ACTION")
                        .HasFilter("MODULE IS NOT NULL AND ACTION IS NOT NULL");

                    b.ToTable("PERMISSIONS", (string)null);
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROLE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id")
                        .HasName("PK_ROLES");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_ROLES_NAME");

                    b.ToTable("ROLES", (string)null);
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.Identity.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROLE_PERMISSION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("GRANTED_AT")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<int?>("GrantedBy")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GRANTED_BY");

                    b.Property<int>("PermissionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERMISSION_ID");

                    b.Property<int>("RoleId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROLE_ID");

                    b.HasKey("Id")
                        .HasName("PK_ROLE_PERMISSIONS");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_ROLE_PERMISSIONS_ROLE_PERMISSION");

                    b.ToTable("ROLE_PERMISSIONS", (string)null);
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("BRANCH");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_LOGIN_AT");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id")
                        .HasName("PK_USERS");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_USERS_EMAIL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_USERS_USERNAME");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.Identity.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ROLE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ASSIGNED_AT")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ASSIGNED_BY");

                    b.Property<int>("RoleId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROLE_ID");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id")
                        .HasName("PK_USER_ROLES");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("IX_USER_ROLES_USER_ROLE");

                    b.ToTable("USER_ROLES", (string)null);
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.AccountMast", b =>
                {
                    b.HasOne("RegistrationPortal.Server.Entities.CustMast", "CustMast")
                        .WithMany("AccountMasts")
                        .HasForeignKey("CustId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_acc_cust");

                    b.Navigation("CustMast");
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.CustomerDocument", b =>
                {
                    b.HasOne("RegistrationPortal.Server.Entities.CustMast", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.CustomerFatca", b =>
                {
                    b.HasOne("RegistrationPortal.Server.Entities.CustMast", "Customer")
                        .WithOne("CustomerFatca")
                        .HasForeignKey("RegistrationPortal.Server.Entities.CustomerFatca", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fatca_customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.Identity.RolePermission", b =>
                {
                    b.HasOne("RegistrationPortal.Server.Entities.Identity.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ROLE_PERMISSIONS_PERMISSION");

                    b.HasOne("RegistrationPortal.Server.Entities.Identity.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ROLE_PERMISSIONS_ROLE");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.Identity.UserRole", b =>
                {
                    b.HasOne("RegistrationPortal.Server.Entities.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLES_ROLE");

                    b.HasOne("RegistrationPortal.Server.Entities.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLES_USER");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.CustMast", b =>
                {
                    b.Navigation("AccountMasts");

                    b.Navigation("CustomerFatca");
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.Identity.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.Identity.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RegistrationPortal.Server.Entities.Identity.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
