import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class FormOptionsService {
  
  // Gender Options
  genderOptions = [
    { label: 'ذكر', value: 'M' },
    { label: 'أنثى', value: 'F' }
  ];

  // Religion Options
  religionOptions = [
    { label: 'مسلم', value: 'MUSLIM' },
    { label: 'مسيحي', value: 'CHRISTIAN' },
    { label: 'غير ذلك', value: 'OTHER' }
  ];

  // Education Options
  educationOptions = [
    { label: 'بدون تعليم', value: 'NONE' },
    { label: 'ابتدائي', value: 'PRIMARY' },
    { label: 'متوسط', value: 'MIDDLE' },
    { label: 'ثانوي', value: 'SECONDARY' },
    { label: 'جامعي', value: 'UNIVERSITY' },
    { label: 'دراسات عليا', value: 'POST_GRADUATE' },
    { label: 'دبلوم', value: 'DIPLOMA' }
  ];

  // Marital Status Options
  maritalStatusOptions = [
    { label: 'أعزب', value: 'SINGLE' },
    { label: 'متزوج', value: 'MARRIED' },
    { label: 'مطلق', value: 'DIVORCED' },
    { label: 'أرمل', value: 'WIDOWED' }
  ];

  // Nationality Options
  nationalityOptions = [
    { label: 'سوداني', value: 'Sudanese' },
    { label: 'مصري', value: 'Egyptian' },
    { label: 'سعودي', value: 'Saudi' },
    { label: 'إماراتي', value: 'Emirati' },
    { label: 'قطري', value: 'Qatari' },
    { label: 'كويتي', value: 'Kuwaiti' },
    { label: 'بحريني', value: 'Bahraini' },
    { label: 'عماني', value: 'Omani' },
    { label: 'يمني', value: 'Yemeni' },
    { label: 'عراقي', value: 'Iraqi' },
    { label: 'أردني', value: 'Jordanian' },
    { label: 'لبناني', value: 'Lebanese' },
    { label: 'سوري', value: 'Syrian' },
    { label: 'فلسطيني', value: 'Palestinian' },
    { label: 'ليبي', value: 'Libyan' },
    { label: 'تونسي', value: 'Tunisian' },
    { label: 'جزائري', value: 'Algerian' },
    { label: 'مغربي', value: 'Moroccan' },
    { label: 'موريتاني', value: 'Mauritanian' },
    { label: 'غير ذلك', value: 'Other' }
  ];

  // ID Type Options
  idTypeOptions = [
    { label: 'جواز سفر', value: 'PASSPORT' },
    { label: 'رخصة قيادة', value: 'DRIVING_LICENSE' },
    { label: 'بطاقة قومية', value: 'NATIONAL_ID' },
  ];

  // Account Type Options
  accountTypeOptions = [
    { label: 'حساب جاري', value: '20101' },
    { label: 'حساب توفير', value: '20102' },
    { label: 'حساب وديعة', value: '20103' }
  ];

  // Currency Options
  currencyOptions = [
    { label: 'SDG - جنيه سوداني', value: '001' }
  ];

  // Countries of Birth (Arabic names with English country names)
  countriesOfBirth = [
    { label: 'السودان', value: 'Sudan' },
    { label: 'مصر', value: 'Egypt' },
    { label: 'ليبيا', value: 'Libya' },
    { label: 'تونس', value: 'Tunisia' },
    { label: 'الجزائر', value: 'Algeria' },
    { label: 'المغرب', value: 'Morocco' },
    { label: 'موريتانيا', value: 'Mauritania' },
    { label: 'السعودية', value: 'Saudi Arabia' },
    { label: 'اليمن', value: 'Yemen' },
    { label: 'عمان', value: 'Oman' },
    { label: 'الإمارات العربية المتحدة', value: 'United Arab Emirates' },
    { label: 'قطر', value: 'Qatar' },
    { label: 'البحرين', value: 'Bahrain' },
    { label: 'الكويت', value: 'Kuwait' },
    { label: 'العراق', value: 'Iraq' },
    { label: 'الأردن', value: 'Jordan' },
    { label: 'لبنان', value: 'Lebanon' },
    { label: 'سوريا', value: 'Syria' },
    { label: 'فلسطين', value: 'Palestine' },
    { label: 'إيران', value: 'Iran' },
    { label: 'تركيا', value: 'Turkey' },
    { label: 'أفغانستان', value: 'Afghanistan' },
    { label: 'باكستان', value: 'Pakistan' },
    { label: 'الهند', value: 'India' },
    { label: 'بنغلاديش', value: 'Bangladesh' },
    { label: 'سريلانكا', value: 'Sri Lanka' },
    { label: 'نيبال', value: 'Nepal' },
    { label: 'بوتان', value: 'Bhutan' },
    { label: 'مالديف', value: 'Maldives' },
    { label: 'ماليزيا', value: 'Malaysia' },
    { label: 'إندونيسيا', value: 'Indonesia' },
    { label: 'الفلبين', value: 'Philippines' },
    { label: 'تايلاند', value: 'Thailand' },
    { label: 'فيتنام', value: 'Vietnam' },
    { label: 'كمبوديا', value: 'Cambodia' },
    { label: 'لاوس', value: 'Laos' },
    { label: 'ميانمار', value: 'Myanmar' },
    { label: 'سنغافورة', value: 'Singapore' },
    { label: 'بروناي', value: 'Brunei' },
    { label: 'تيمور الشرقية', value: 'East Timor' },
    { label: 'اليابان', value: 'Japan' },
    { label: 'كوريا الجنوبية', value: 'South Korea' },
    { label: 'كوريا الشمالية', value: 'North Korea' },
    { label: 'الصين', value: 'China' },
    { label: 'منغوليا', value: 'Mongolia' },
    { label: 'تايوان', value: 'Taiwan' },
    { label: 'هونغ كونغ', value: 'Hong Kong' },
    { label: 'روسيا', value: 'Russia' },
    { label: 'ألمانيا', value: 'Germany' },
    { label: 'فرنسا', value: 'France' },
    { label: 'المملكة المتحدة', value: 'United Kingdom' },
    { label: 'إيطاليا', value: 'Italy' },
    { label: 'إسبانيا', value: 'Spain' },
    { label: 'هولندا', value: 'Netherlands' },
    { label: 'بلجيكا', value: 'Belgium' },
    { label: 'النمسا', value: 'Austria' },
    { label: 'سويسرا', value: 'Switzerland' },
    { label: 'السويد', value: 'Sweden' },
    { label: 'النرويج', value: 'Norway' },
    { label: 'الدنمارك', value: 'Denmark' },
    { label: 'فنلندا', value: 'Finland' },
    { label: 'أيسلندا', value: 'Iceland' },
    { label: 'أيرلندا', value: 'Ireland' },
    { label: 'البرتغال', value: 'Portugal' },
    { label: 'اليونان', value: 'Greece' },
    { label: 'بولندا', value: 'Poland' },
    { label: 'جمهورية التشيك', value: 'Czech Republic' },
    { label: 'سلوفاكيا', value: 'Slovakia' },
    { label: 'المجر', value: 'Hungary' },
    { label: 'رومانيا', value: 'Romania' },
    { label: 'بلغاريا', value: 'Bulgaria' },
    { label: 'كرواتيا', value: 'Croatia' },
    { label: 'صربيا', value: 'Serbia' },
    { label: 'البوسنة والهرسك', value: 'Bosnia and Herzegovina' },
    { label: 'الجبل الأسود', value: 'Montenegro' },
    { label: 'ألبانيا', value: 'Albania' },
    { label: 'مقدونيا الشمالية', value: 'North Macedonia' },
    { label: 'سلوفينيا', value: 'Slovenia' },
    { label: 'استونيا', value: 'Estonia' },
    { label: 'لاتفيا', value: 'Latvia' },
    { label: 'ليتوانيا', value: 'Lithuania' },
    { label: 'أوكرانيا', value: 'Ukraine' },
    { label: 'بيلاروس', value: 'Belarus' },
    { label: 'مولدوفا', value: 'Moldova' },
    { label: 'جورجيا', value: 'Georgia' },
    { label: 'أرمينيا', value: 'Armenia' },
    { label: 'أذربيجان', value: 'Azerbaijan' },
    { label: 'قبرص', value: 'Cyprus' },
    { label: 'مالطا', value: 'Malta' },
    { label: 'لوكسمبورغ', value: 'Luxembourg' },
    { label: 'موناكو', value: 'Monaco' },
    { label: 'أندورا', value: 'Andorra' },
    { label: 'سان مارينو', value: 'San Marino' },
    { label: 'الفاتيكان', value: 'Vatican City' },
    { label: 'ليختنشتاين', value: 'Liechtenstein' },
    { label: 'الولايات المتحدة الأمريكية', value: 'United States' },
    { label: 'كندا', value: 'Canada' },
    { label: 'المكسيك', value: 'Mexico' },
    { label: 'غواتيمالا', value: 'Guatemala' },
    { label: 'بليز', value: 'Belize' },
    { label: 'هندوراس', value: 'Honduras' },
    { label: 'السلفادور', value: 'El Salvador' },
    { label: 'نيكاراغوا', value: 'Nicaragua' },
    { label: 'كوستاريكا', value: 'Costa Rica' },
    { label: 'بنما', value: 'Panama' },
    { label: 'كوبا', value: 'Cuba' },
    { label: 'هايتي', value: 'Haiti' },
    { label: 'جمهورية الدومينيكان', value: 'Dominican Republic' },
    { label: 'جامايكا', value: 'Jamaica' },
    { label: 'بورتوريكو', value: 'Puerto Rico' },
    { label: 'ترينيداد وتوباغو', value: 'Trinidad and Tobago' },
    { label: 'باربادوس', value: 'Barbados' },
    { label: 'غيانا', value: 'Guyana' },
    { label: 'سورينام', value: 'Suriname' },
    { label: 'فنزويلا', value: 'Venezuela' },
    { label: 'كولومبيا', value: 'Colombia' },
    { label: 'الإكوادور', value: 'Ecuador' },
    { label: 'بيرو', value: 'Peru' },
    { label: 'بوليفيا', value: 'Bolivia' },
    { label: 'تشيلي', value: 'Chile' },
    { label: 'الأرجنتين', value: 'Argentina' },
    { label: 'أوروغواي', value: 'Uruguay' },
    { label: 'باراغواي', value: 'Paraguay' },
    { label: 'البرازيل', value: 'Brazil' },
    { label: 'أستراليا', value: 'Australia' },
    { label: 'نيوزيلندا', value: 'New Zealand' },
    { label: 'بابوا غينيا الجديدة', value: 'Papua New Guinea' },
    { label: 'فيجي', value: 'Fiji' },
    { label: 'جزر سليمان', value: 'Solomon Islands' },
    { label: 'فانواتو', value: 'Vanuatu' },
    { label: 'ساموا', value: 'Samoa' },
    { label: 'تونغا', value: 'Tonga' },
    { label: 'كيريباتي', value: 'Kiribati' },
    { label: 'ناورو', value: 'Nauru' },
    { label: 'توفالو', value: 'Tuvalu' },
    { label: 'جزر مارشال', value: 'Marshall Islands' },
    { label: 'بالاو', value: 'Palau' },
    { label: 'ميكرونيزيا', value: 'Micronesia' },
    { label: 'جنوب أفريقيا', value: 'South Africa' },
    { label: 'نيجيريا', value: 'Nigeria' },
    { label: 'كينيا', value: 'Kenya' },
    { label: 'تنزانيا', value: 'Tanzania' },
    { label: 'أوغندا', value: 'Uganda' },
    { label: 'رواندا', value: 'Rwanda' },
    { label: 'بوروندي', value: 'Burundi' },
    { label: 'إثيوبيا', value: 'Ethiopia' },
    { label: 'إريتريا', value: 'Eritrea' },
    { label: 'جيبوتي', value: 'Djibouti' },
    { label: 'الصومال', value: 'Somalia' },
    { label: 'جزر القمر', value: 'Comoros' },
    { label: 'مدغشقر', value: 'Madagascar' },
    { label: 'موريشيوس', value: 'Mauritius' },
    { label: 'سيشل', value: 'Seychelles' },
    { label: 'غانا', value: 'Ghana' },
    { label: 'ساحل العاج', value: 'Ivory Coast' },
    { label: 'غينيا', value: 'Guinea' },
    { label: 'غينيا بيساو', value: 'Guinea-Bissau' },
    { label: 'سيراليون', value: 'Sierra Leone' },
    { label: 'ليبيريا', value: 'Liberia' },
    { label: 'توغو', value: 'Togo' },
    { label: 'بنين', value: 'Benin' },
    { label: 'النيجر', value: 'Niger' },
    { label: 'مالي', value: 'Mali' },
    { label: 'بوركينا فاسو', value: 'Burkina Faso' },
    { label: 'تشاد', value: 'Chad' },
    { label: 'السودان', value: 'Sudan' },
    { label: 'جمهورية أفريقيا الوسطى', value: 'Central African Republic' },
    { label: 'الكاميرون', value: 'Cameroon' },
    { label: 'غينيا الاستوائية', value: 'Equatorial Guinea' },
    { label: 'الغابون', value: 'Gabon' },
    { label: 'الكونغو', value: 'Congo' },
    { label: 'الكونغو الديمقراطية', value: 'Democratic Republic of Congo' },
    { label: 'أنغولا', value: 'Angola' },
    { label: 'زامبيا', value: 'Zambia' },
    { label: 'ملاوي', value: 'Malawi' },
    { label: 'موزامبيق', value: 'Mozambique' },

    { label: 'زمبابوي', value: 'Zimbabwe' },
    { label: 'بوتسوانا', value: 'Botswana' },
    { label: 'ناميبيا', value: 'Namibia' },
    { label: 'ليسوتو', value: 'Lesotho' },
    { label: 'إسواتيني', value: 'Eswatini' },
    { label: 'موريتانيا', value: 'Mauritania' },
    { label: 'الرأس الأخضر', value: 'Cape Verde' },
    { label: 'غامبيا', value: 'Gambia' },
    { label: 'السنغال', value: 'Senegal' },
    { label: 'موريتانيا', value: 'Mauritania' }
  ];

  // Country Code Options
  countryCodeOptions = [
    { label: '+249 السودان', value: '+249' },
    { label: '+20 مصر', value: '+20' },
    { label: '+966 السعودية', value: '+966' },
    { label: '+971 الإمارات', value: '+971' },
    { label: '+965 الكويت', value: '+965' },
    { label: '+973 البحرين', value: '+973' },
    { label: '+974 قطر', value: '+974' },
    { label: '+968 عمان', value: '+968' },
    { label: '+962 الأردن', value: '+962' },
    { label: '+961 لبنان', value: '+961' },
    { label: '+963 سوريا', value: '+963' },
    { label: '+970 فلسطين', value: '+970' },
    { label: '+218 ليبيا', value: '+218' },
    { label: '+216 تونس', value: '+216' },
    { label: '+213 الجزائر', value: '+213' },
    { label: '+212 المغرب', value: '+212' },
    { label: '+222 موريتانيا', value: '+222' },
    { label: '+964 العراق', value: '+964' },
    { label: '+98 إيران', value: '+98' },
    { label: '+90 تركيا', value: '+90' },
    { label: '+92 باكستان', value: '+92' },
    { label: '+91 الهند', value: '+91' },
    { label: '+880 بنغلاديش', value: '+880' },
    { label: '+94 سريلانكا', value: '+94' },
    { label: '+977 نيبال', value: '+977' },
    { label: '+60 ماليزيا', value: '+60' },
    { label: '+62 إندونيسيا', value: '+62' },
    { label: '+63 الفلبين', value: '+63' },
    { label: '+66 تايلاند', value: '+66' },
    { label: '+84 فيتنام', value: '+84' },
    { label: '+81 اليابان', value: '+81' },
    { label: '+82 كوريا الجنوبية', value: '+82' },
    { label: '+86 الصين', value: '+86' },
    { label: '+7 روسيا', value: '+7' },
    { label: '+49 ألمانيا', value: '+49' },
    { label: '+33 فرنسا', value: '+33' },
    { label: '+44 المملكة المتحدة', value: '+44' },
    { label: '+39 إيطاليا', value: '+39' },
    { label: '+34 إسبانيا', value: '+34' },
    { label: '+31 هولندا', value: '+31' },
    { label: '+43 النمسا', value: '+43' },
    { label: '+41 سويسرا', value: '+41' },
    { label: '+46 السويد', value: '+46' },
    { label: '+47 النرويج', value: '+47' },
    { label: '+45 الدنمارك', value: '+45' },
    { label: '+358 فنلندا', value: '+358' },
    { label: '+354 أيسلندا', value: '+354' },
    { label: '+353 أيرلندا', value: '+353' },
    { label: '+351 البرتغال', value: '+351' },
    { label: '+30 اليونان', value: '+30' },
    { label: '+48 بولندا', value: '+48' },
    { label: '+420 جمهورية التشيك', value: '+420' },
    { label: '+421 سلوفاكيا', value: '+421' },
    { label: '+36 المجر', value: '+36' },
    { label: '+40 رومانيا', value: '+40' },
    { label: '+359 بلغاريا', value: '+359' },
    { label: '+385 كرواتيا', value: '+385' },
    { label: '+381 صربيا', value: '+381' },
    { label: '+387 البوسنة والهرسك', value: '+387' },
    { label: '+382 الجبل الأسود', value: '+382' },
    { label: '+355 ألبانيا', value: '+355' },
    { label: '+389 مقدونيا الشمالية', value: '+389' },
    { label: '+386 سلوفينيا', value: '+386' },
    { label: '+372 استونيا', value: '+372' },
    { label: '+371 لاتفيا', value: '+371' },
    { label: '+370 ليتوانيا', value: '+370' },
    { label: '+380 أوكرانيا', value: '+380' },
    { label: '+375 بيلاروس', value: '+375' },
    { label: '+373 مولدوفا', value: '+373' },
    { label: '+995 جورجيا', value: '+995' },
    { label: '+374 أرمينيا', value: '+374' },
    { label: '+994 أذربيجان', value: '+994' },
    { label: '+357 قبرص', value: '+357' },
    { label: '+356 مالطا', value: '+356' },
    { label: '+352 لوكسمبورغ', value: '+352' },
    { label: '+377 موناكو', value: '+377' },
    { label: '+376 أندورا', value: '+376' },
    { label: '+378 سان مارينو', value: '+378' },
    { label: '+379 الفاتيكان', value: '+379' },
    { label: '+423 ليختنشتاين', value: '+423' },
    { label: '+1 الولايات المتحدة الأمريكية', value: '+1' },
    { label: '+1 كندا', value: '+1' },
    { label: '+52 المكسيك', value: '+52' },
    { label: '+502 غواتيمالا', value: '+502' },
    { label: '+501 بليز', value: '+501' },
    { label: '+504 هندوراس', value: '+504' },
    { label: '+503 السلفادور', value: '+503' },
    { label: '+505 نيكاراغوا', value: '+505' },
    { label: '+506 كوستاريكا', value: '+506' },
    { label: '+507 بنما', value: '+507' },
    { label: '+53 كوبا', value: '+53' },
    { label: '+509 هايتي', value: '+509' },
    { label: '+1-809 جمهورية الدومينيكان', value: '+1-809' },
    { label: '+1-876 جامايكا', value: '+1-876' },
    { label: '+1-787 بورتوريكو', value: '+1-787' },
    { label: '+1-868 ترينيداد وتوباغو', value: '+1-868' },
    { label: '+1-246 باربادوس', value: '+1-246' },
    { label: '+592 غيانا', value: '+592' },
    { label: '+597 سورينام', value: '+597' },
    { label: '+58 فنزويلا', value: '+58' },
    { label: '+57 كولومبيا', value: '+57' },
    { label: '+593 الإكوادور', value: '+593' },
    { label: '+51 بيرو', value: '+51' },
    { label: '+591 بوليفيا', value: '+591' },
    { label: '+56 تشيلي', value: '+56' },
    { label: '+54 الأرجنتين', value: '+54' },
    { label: '+598 أوروغواي', value: '+598' },
    { label: '+595 باراغواي', value: '+595' },
    { label: '+55 البرازيل', value: '+55' },
    { label: '+61 أستراليا', value: '+61' },
    { label: '+64 نيوزيلندا', value: '+64' },
    { label: '+675 بابوا غينيا الجديدة', value: '+675' },
    { label: '+679 فيجي', value: '+679' },
    { label: '+677 جزر سليمان', value: '+677' },
    { label: '+678 فانواتو', value: '+678' },
    { label: '+685 ساموا', value: '+685' },
    { label: '+676 تونغا', value: '+676' },
    { label: '+686 كيريباتي', value: '+686' },
    { label: '+674 ناورو', value: '+674' },
    { label: '+688 توفالو', value: '+688' },
    { label: '+692 جزر مارشال', value: '+692' },
    { label: '+680 بالاو', value: '+680' },
    { label: '+691 ميكرونيزيا', value: '+691' },
    { label: '+27 جنوب أفريقيا', value: '+27' },
    { label: '+234 نيجيريا', value: '+234' },
    { label: '+254 كينيا', value: '+254' },
    { label: '+255 تنزانيا', value: '+255' },
    { label: '+256 أوغندا', value: '+256' },
    { label: '+250 رواندا', value: '+250' },
    { label: '+257 بوروندي', value: '+257' },
    { label: '+251 إثيوبيا', value: '+251' },
    { label: '+291 إريتريا', value: '+291' },
    { label: '+253 جيبوتي', value: '+253' },
    { label: '+252 الصومال', value: '+252' },
    { label: '+269 جزر القمر', value: '+269' },
    { label: '+261 مدغشقر', value: '+261' },
    { label: '+230 موريشيوس', value: '+230' },
    { label: '+248 سيشل', value: '+248' },
    { label: '+233 غانا', value: '+233' },
    { label: '+225 ساحل العاج', value: '+225' },
    { label: '+224 غينيا', value: '+224' },
    { label: '+245 غينيا بيساو', value: '+245' },
    { label: '+232 سيراليون', value: '+232' },
    { label: '+231 ليبيريا', value: '+231' },
    { label: '+228 توغو', value: '+228' },
    { label: '+229 بنين', value: '+229' },
    { label: '+227 النيجر', value: '+227' },
    { label: '+223 مالي', value: '+223' },
    { label: '+226 بوركينا فاسو', value: '+226' },
    { label: '+235 تشاد', value: '+235' },
    { label: '+236 جمهورية أفريقيا الوسطى', value: '+236' },
    { label: '+237 الكاميرون', value: '+237' },
    { label: '+240 غينيا الاستوائية', value: '+240' },
    { label: '+241 الغابون', value: '+241' },
    { label: '+242 الكونغو', value: '+242' },
    { label: '+243 الكونغو الديمقراطية', value: '+243' },
    { label: '+244 أنغولا', value: '+244' },
    { label: '+260 زامبيا', value: '+260' },
    { label: '+265 ملاوي', value: '+265' },
    { label: '+258 موزامبيق', value: '+258' },
    { label: '+263 زمبابوي', value: '+263' },
    { label: '+267 بوتسوانا', value: '+267' },
    { label: '+264 ناميبيا', value: '+264' },
    { label: '+266 ليسوتو', value: '+266' },
    { label: '+268 إسواتيني', value: '+268' },
    { label: '+222 الرأس الأخضر', value: '+222' },
    { label: '+220 غامبيا', value: '+220' },
    { label: '+221 السنغال', value: '+221' }
  ];

  // Branch Options
  branches = [
    { label: 'فرع مدني', value: '001' },
    { label: 'فرع الحصاحيصا', value: '002' },
    { label: 'فرع المناقل', value: '003' },
    { label: 'فرع رفاعة', value: '004' },
    { label: 'فرع سنار', value: '005' },
    { label: 'فرع الأمم', value: '006' },
    { label: 'فرع القضارف', value: '007' },
    { label: 'فرع كوستي', value: '008' },
    { label: 'فرع السوكي', value: '009' },
    { label: 'فرع السوق الجديد', value: '011' },
    { label: 'فرع سنجة', value: '012' },
    { label: 'فرع طابت', value: '013' },
    { label: 'فرع عطبره', value: '015' },
    { label: 'فرع الفاو', value: '016' },
    { label: 'فرع تمبول', value: '017' },
    { label: 'فرع الأبيض', value: '018' },
    { label: 'فرع أمدرمان', value: '019' },
    { label: 'فرع شندي', value: '020' },
    { label: 'فرع ربك', value: '021' },
    { label: 'فرع الخرطوم جنوب', value: '022' },
    { label: 'فرع كسلا', value: '024' },
    { label: 'فرع بارا', value: '025' },
    { label: 'فرع المنطقة أمدرمان', value: '026' },
    { label: 'فرع الشواك', value: '027' },
    { label: 'فرع بورتسودان', value: '028' },
    { label: 'فرع جامعة الجزيرة', value: '030' },
    { label: 'المركز الرئيس', value: '031' },
    { label: 'فرع السوق العربي', value: '032' },
    { label: 'فرع الدلنج', value: '033' },
    { label: 'فرع دنقلا', value: '034' },
    { label: 'فرع بحري', value: '035' },
    { label: 'فرع السوق المحلي', value: '036' },
    { label: 'فرع الدمازين', value: '037' },
    { label: 'فرع نيالا', value: '038' },
    { label: 'فرع بربر', value: '039' },
    { label: 'فرع الفاشر', value: '040' },
    { label: 'فرع الجنينة', value: '041' },
    { label: 'فرع الخوي', value: '042' },
    { label: 'فرع الكومة', value: '043' },
    { label: 'فرع الصباغ', value: '044' },
    { label: 'فرع النموزجي', value: '045' },
    { label: 'فرع كادقلي', value: '046' },
    { label: 'فرع الكاملين', value: '047' },
    { label: 'فرع أبوحمد', value: '048' },
    { label: 'فرع جامعة النيلين', value: '049' },
    { label: 'فرع سوق ليبيا', value: '050' },
    { label: 'فرع زالنجي', value: '051' },
    { label: 'فرع السوق المركزي', value: '052' },
    { label: 'فرع حلفا', value: '053' },
    { label: 'فرع الضعين', value: '054' },
    { label: 'فرع الفولة', value: '055' },
    { label: 'فرع القرشي', value: '056' },
    { label: 'فرع ود راوة', value: '057' },
    { label: 'فرع أبوكارينكا', value: '058' },
    { label: 'فرع الدامر', value: '059' },
    { label: 'فرع الرصيرص', value: '060' }
  ];

  constructor() { }
}
