-- Add BRANCH column to USERS table
ALTER TABLE SSDBONLINE.USERS 
ADD BRANCH VARCHAR2(50) NULL;

-- Add index for better performance on BRANCH column
CREATE INDEX IX_USERS_BRANCH ON SSDBONLINE.USERS(BRANCH);
